### ISSUE TITLE
Qualcomm Atheros AR5B125 and related WiFi cards broken after installing fix.

### ISSUE THREAD

**Issue by Pokemonfan1000** [Skulltrail192/One-Core-API-Binaries#174] opened 2023-08-20 01:26 UTC
Hi! I posted a while back that Qualcomm Atheros AR5B125 WiFi and related cards break after installing this kernel (whereas they worked prior to it being installed) while Intel Centrino cards work just fine (idk about PCI-E Realtek and Broadcomm WiFi cards, but Realtek USB WiFi works just fine), and I was wondering if a fix for the Atheros cards has been found. The Atheros card is the only card that supports WiFi under Windows 2000 thanks to blackwingcat (Intel Centrino does not support W2K), so I would like to have that working so I can put it back into my laptop. After installing this kernel, the Atheros WiFi driver will throw a Code 10 error. I did update to 3.0.0, but have not tried the card under this version yet.

**Comment by Skulltrail192** [comment] 2023-08-27 23:28
Welll, the problem is Code 10 or can't see any wifi connection avaliable? Because i can't see any wifi really.

**Comment by Skulltrail192** [comment] 2023-08-31 02:52
Same #170

**Comment by Skulltrail192** [comment] 2023-09-08 17:38
Fixed on version 3.0.1. Maybe you can't uninstall current driver package. For solution, i recommend change ksedd driver with RTM driver (5.1.2600.5512)

**Closed by Skulltrail192** 2023-09-08 17:38 UTC
Labels: bug, duplicate, regression
