### ISSUE TITLE
0xDEADBEEF bsod

### ISSUE THREAD

**Issue by cesar300** [Skulltrail192/One-Core-API-Binaries#42] opened 2021-10-26 09:26 UTC
I have installed this on a Windows XP virtual machine with vmware and after install the base package and reboot I got those bsod.
I used an iso with the patches of integral edition with and without kernel patch. I need these mods for future testing on real hardware.

**Comment by Skulltrail192** [comment] 2021-11-18 15:38
Hey, can you send to Shorthorn Project e-mail the iso used on this installation? E-mail: shorthornproject@outlook.com

**Comment by cesar300** [comment] 2021-11-18 16:12
File is too large (660 MB) to send via attachment. Instead I'll send a google drive download link.
Thanks

**Comment by cesar300** [comment] 2022-02-16 14:16
The new version 2.2 is still throwing this BSOD.

**Comment by Skulltrail192** [comment] 2022-06-29 04:41
This issue was fixed?

**Comment by cesar300** [comment] 2022-06-29 05:48
Unfortunately not yet.

**Comment by Skulltrail192** [comment] 2022-06-29 11:14
So, please, send here the link of google drive to download

**Comment by Skulltrail192** [comment] 2022-06-29 11:43
And tell me about environment:
- Vmware specs used;
- Windows XP version used: has updates installed? Is vanilla?

**Comment by cesar300** [comment] 2022-06-29 13:29
https://drive.google.com/file/d/14hByqsxhvxUkkJseLBXDMdZMhPscs88q/view?usp=sharing
VMware 16.2.3
Windows XP Pro SP3 Spanish with the following fixes from integral edition:
- Generic SATA AHCI driver
- USB 3.x xhci generic driver
- ACPI patch
- PAE 4GB ram patch
- Kernel mode driver framework 1.11
- Live USB setup

**Comment by cesar300** [comment] 2022-06-29 15:06
> Are you installed with USB 3.0 and AHCI options on Vmware?

Don't mind in Vmware but in real hardware I need those fixes

**Comment by posreadyxp** [comment] 2022-06-30 18:39
Same this BSoD. I tried to install XP (on modern hardware with NVMe (Samsung drivers), SATA drivers, USB 3.x support, ACPI, PAE 128 GB, Kernel Mode driver framework 1.11) and got error now

**Comment by Skulltrail192** [comment] 2022-06-30 23:26
Well, the issue is produced by ntoskrnl_emu. It uses a tecnhique to find a address of some functions using hex address. The problem is: the kernel of One-Core-API is a custom kernel, so, the address are differents. I think ntoskrnl_emu is completly imcompatible with one-core-api. And, all functions implemented on ntoskrnl_emu is implemented on One-Core-API kernel. the way is replace references of ntoskrn_emu on driver with ntoskrnl original.

**Comment by JakoDel** [comment] 2022-07-20 10:52
> Well, the issue is produced by ntoskrnl_emu. It uses a tecnhique to find a address of some functions using hex address. The problem is: the kernel of One-Core-API is a custom kernel, so, the address are differents. I think ntoskrnl_emu is completly imcompatible with one-core-api. And, all functions implemented on ntoskrnl_emu is implemented on One-Core-API kernel. the way is replace references of ntoskrn_emu on driver with ntoskrnl original.

will you ever work on a fix (if there is one) for this issue? I got XP fully working on my new coffee lake system but it's quite useless without your amazing piece of software :/

**Comment by Skulltrail192** [comment] 2022-08-06 04:07
Yes, i'm working a workaround to fix it. I will release a custom version of ntoskrnl_emu.

**Comment by Skulltrail192** [comment] 2022-08-25 03:42
Hello, i made a special version of Ntoskrnl_emu and it's working on XP/Server 2003 and XP x64. On end-of-month i will release new version.

**Comment by posreadyxp** [comment] 2022-08-25 05:46
> Hello, i made a special version of Ntoskrnl_emu and it's working on XP/Server 2003 and XP x64. On end-of-month i will release new version.

That's cool, i'm wait Your release =)

**Comment by JakoDel** [comment] 2022-08-25 19:30
> Hello, i made a special version of Ntoskrnl_emu and it's working on XP/Server 2003 and XP x64. On end-of-month i will release new version.

thanks a lot!

**Comment by Skulltrail192** [comment] 2022-09-02 12:19
Fixed on version 2.9. Close this issue.

**Closed by Skulltrail192** 2022-09-02 12:19 UTC
